# Generated by Django 5.2.1 on 2025-07-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_customer_order_orderproduct_shippingadress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказах'},
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактный номер'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='state',
            field=models.CharField(max_length=255, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='streat',
            field=models.CharField(max_length=255, verbose_name='Улица'),
        ),
    ]
