# Generated by Django 5.2.1 on 2025-07-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_orderproduct_options_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingadress',
            options={'verbose_name': 'Адрес доставки', 'verbose_name_plural': 'Адреса доставки'},
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='streat',
            new_name='street',
        ),
    ]
